import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Link href={'/'}>index</Link>
        &nbsp;
        <Link href={'/search'}>search</Link>
        &nbsp;
        <Link href={'/book/1'}>book/1</Link>
        {children}
        </body>
    </html>
  )
}

 